name: tramo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  fl_chart: ^0.65.0
  flutter_svg: 2.0.5
  font_awesome_flutter: 10.6.0
  get: 4.6.6
  google_fonts: 5.0.0
  intl: ^0.19.0
  shared_preferences: 2.2.2
  path_provider: 2.1.2
  idb_shim: 2.3.2
  dio: 5.4.3+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/square.svg
    - assets/icons/square_big.svg
  uses-material-design: true

